### ISSUE TITLE
User can spam unban requests

### ISSUE THREAD

**Issue by Shayshon** [2Lost4This/discord-ban-appeals#1]
Hi! I seem to have found a bug where if a user clicks the back arrow after submitting their unban request, they can spam the submit button which also spams the appeals channel.

**Comment by 2Lost4This** [comment]
Heyo, thanks for reporting, im not using this anymore because it seems like nobody is using this

**Comment by Shayshon** [comment]
> Heyo, thanks for reporting, im not using this anymore because it seems like nobody is using this
Oh, that's sad ):

**Comment by 2Lost4This** [comment]
> Oh, that's sad ):
> > Heyo, thanks for reporting, im not using this anymore because it seems like nobody is using this
> 

Its okey
